# window rule

# All windows
windowrule = no_blur 1, match:title = .* # no blur, convenient for specifying blur
windowrule = no_shadow 1, match:float = 0 # no shadow, more flat

# Dialogs float
windowrule = float 1, match:title = ^.*(Open|Choose|Select|Save|Upload|File Upload).*.*
