bind = SUPERSHIFT, X, exec, pidof wlogout || wlogout

# window rule
windowrule = float 1, match:class = ^(wlogout)$
windowrule = move 0 0, match:class = ^(wlogout)$
windowrule = size 100% 100%, match:class = ^(wlogout)$
windowrule = animation slide, match:class = ^(wlogout)$
