{
  config,
  lib,
  namespace,
  ...
}:
let
  inherit (lib)
    types
    mkOption
    optionalAttrs
    ;
  cfg = config.${namespace}.apps.ssh;

  knownHostsFiles = [
    "/etc/ssh/ssh_known_hosts"
  ]
  ++ (map (name: "/etc/ssh/${name}") cfg.knownHostsFileNames)
  ++ cfg.knownHostsFiles;
in
{
  options.${namespace}.apps.ssh = with types; {
    knownHostsFileNames = mkOption {
      default = [ ];
      type = listOf str;
    };
    knownHostsFiles = mkOption {
      default = [ ];
      type = listOf path;
      description = ''
        Files containing SSH host keys to set as global known hosts.
        `/etc/ssh/ssh_known_hosts` (which is
        generated by {option}`programs.ssh.knownHosts`) is
        always included.
      '';
      example = lib.literalExpression ''
        [
          ./known_hosts
          (writeText "github.keys" '''
            github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
            github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
            github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          ''')
        ]
      '';
    };
  };

  config = {
    programs.ssh = {
      inherit (cfg) knownHostsFiles;
    }
    // (optionalAttrs (cfg.knownHostsFileNames != [ ]) {
      extraConfig = "GlobalKnownHostsFile ${builtins.concatStringsSep " " knownHostsFiles}";
    });
  };

}
