hl.config({
  general = {
    layout = "dwindle",
    allow_tearing = false,
    gaps_workspaces = 20,
    gaps_in = 5,
    gaps_out = 10,
    border_size = 1,
    ["col.active_border"] = "rgba(c2c1ffe6)",
    ["col.inactive_border"] = "rgba(c8c5d111)",
  },
  dwindle = {
    preserve_split = true,
    smart_split = false,
    smart_resizing = true,
  },
  input = {
    kb_layout = "us",
    numlock_by_default = false,
    repeat_delay = 250,
    repeat_rate = 35,
    focus_on_close = 1,
    touchpad = {
      natural_scroll = true,
      disable_while_typing = true,
      scroll_factor = 0.3,
    },
  },
  binds = {
    scroll_event_delay = 0,
  },
  cursor = {
    hotspot_padding = 1,
  },
  misc = {
    vrr = 0,
    animate_manual_resizes = false,
    animate_mouse_windowdragging = false,
    disable_hyprland_logo = true,
    force_default_wallpaper = 0,
    on_focus_under_fullscreen = 2,
    allow_session_lock_restore = true,
    middle_click_paste = false,
    focus_on_activate = true,
    session_lock_xray = true,
    mouse_move_enables_dpms = true,
    key_press_enables_dpms = true,
    background_color = "rgb(201f23)",
  },
  debug = {
    error_position = 1,
  },
  gestures = {
    workspace_swipe_distance = 700,
    workspace_swipe_cancel_ratio = 0.15,
    workspace_swipe_min_speed_to_force = 5,
    workspace_swipe_direction_lock = true,
    workspace_swipe_direction_lock_threshold = 10,
    workspace_swipe_create_new = true,
  },
  scrolling = {
    fullscreen_on_one_column = true,
    focus_fit_method = 1,
    column_width = 0.5,
    follow_focus = true,
    follow_min_visible = 0.0,
    explicit_column_widths = "0.35 0.5 0.65 1.0",
  },
  group = {
    ["col.border_active"] = "rgba(c2c1ffe6)",
    ["col.border_inactive"] = "rgba(c8c5d111)",
    ["col.border_locked_active"] = "rgba(c2c1ffe6)",
    ["col.border_locked_inactive"] = "rgba(c8c5d111)",
    groupbar = {
      font_family = "JetBrains Mono NF",
      font_size = 15,
      gradients = true,
      gradient_round_only_edges = false,
      gradient_rounding = 5,
      height = 25,
      indicator_height = 0,
      gaps_in = 3,
      gaps_out = 3,
      text_color = "rgb(2a2a60)",
      ["col.active"] = "rgba(c2c1ffd4)",
      ["col.inactive"] = "rgba(918f9ad4)",
      ["col.locked_active"] = "rgba(c2c1ffd4)",
      ["col.locked_inactive"] = "rgba(c6c4e0d4)",
    },
  },
})
